### ISSUE TITLE
Document how to use an authentication key with the install script

### ISSUE THREAD

**Issue by offbyone** [SierraSoftworks/tailscale-udm#11]
I've been unable to get the installation to work; it does not ask me to perform a login, only starts tailscaled on the UDM pro.

Once I do that, the tailscale up command does not, in fact, work:

```
/mnt/data/tailscale/tailscale up --force-reauth --authkey CENSORED
```

This command just hangs. 

What I can't tell is if that's something in the setup script or in tailscale itself.

**Comment by notheotherben** [comment]
Hi @offbyone,

The tailscale daemon should be writing its logs to `/mnt/data/tailscale/tailscaled.log` which should help clear up whatever is happening.

Behind the scenes, the initial startup will run `tailscale up`, which might be waiting for your auth to complete - you might want to see if there's any active `tailscale` processes and kill them (`ps aux | grep tailscale`) before attempting to run your own.

Please let me know what you find :)

**Comment by offbyone** [comment]
I'll do that. First, though, I have to figure out why `/mnt/data` doesn't appear to be a mount point.

**Comment by notheotherben** [comment]
Oh, interesting - have you installed the [boostchicken-dev](https://github.com/boostchicken-dev/udm-utilities/tree/master/on-boot-script) on-boot script?

**Comment by offbyone** [comment]
I have. I realized what I was doing wrong all along; I was running it from within the unifi-os shell, which is wrong. Might be worth a line in the docs before step 2 to indicate that "You must exit the unifi-os shell before this step". I know that technically the bootchicken install steps say to exit, but I missed that.

**Comment by notheotherben** [comment]
Ah, that'd do it - thanks for letting me know, I'll add a warning there 😄
