### ISSUE TITLE
Questions about upgrading to newer versions

### ISSUE THREAD

**Issue by ovizii** [SierraSoftworks/tailscale-udm#12]
Hi there,

1. version 1. 12.3 is quite old, currently 1.18.2 is the up-to-date version so I was wondering whether you need to do something to get a newer version or if we are simply waiting for tailscale to release a newer arm64 version?
2. your upgrade instructions are to run: /mnt/data/tailscale/upgrade.sh 1.12.3 
3. that doesn't work for me as the script is not executable. 
```
# ls -al /mnt/data/tailscale/upgrade.sh
-rw-r--r--    1 root     root           744 Dec 30 17:29 /mnt/data/tailscale/upgrade.sh
```
4. why do you have to add 1.12.3 to the end of that command, to me it looks like the version is hard-coded in the upgrade script anyway.
5. how do we upgrade to newer version and how to know when there is a new release available?

###edit###
addressing my own points from  #3 #4 and #5
I manually checked and found a newer version available: https://pkgs.tailscale.com/stable/tailscale_1.18.2_arm64.tgz 

after making the upgrade script executable: 
`chmod 744 /mnt/data/tailscale/upgrade.sh`

I installed it successfully:
`/mnt/data/tailscale/upgrade.sh 1.18.2`

**Comment by notheotherben** [comment]
Hi @ovizii,

I'm gonna respond to your questions by number:

1. Yeah, when running the install script you can specify the version to install, however this wasn't particularly easy to do when running `curl | sh` so I've made some changes which should simplify that.
2. Indeed, I've updated the README to make it clear that you should specify the version you wish to upgrade to (as you've done ), let me know if that makes it clearer.
3. Thanks for spotting that, I've updated the install script to make sure that it is executable from the start.
4. You don't, there's a default-fallback version, but that tends to get out of date 😄 
5. You should be notified of a new release on the Tailscale admin dashboard and you can upgrade to the latest version by running the same upgrade command you ran there 👍

**Comment by ovizii** [comment]
Thanks for clarifying, let me close this issue then.
