### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by cvondra** [SierraSoftworks/tailscale-udm#15]
Whenever I attempt to run the install script as listed I get the error:

"curl: (7) Failed to connect to gihub.com port 443: Connection refused"

Any help would be appreciated.

**Comment by notheotherben** [comment]
Sorry about that, that's my fault - `gihub.com` vs `github.com`. Can you try again with the latest install script when you have a chance?

**Comment by cvondra** [comment]
man I glazed right over that too.  thx.
