### ISSUE TITLE
Install Instruction update

### ISSUE THREAD

**Issue by dtel** [SierraSoftworks/tailscale-udm#2]
for the install script to download, curl need -L option. That is
From:
curl https://raw.github.com/SierraSoftworks/tailscale-udm/master/install.sh | sh

To:
curl -L https://raw.github.com/SierraSoftworks/tailscale-udm/master/install.sh | sh

**Comment by notheotherben** [comment]
Thanks, updated - for some reason I didn't get a notification on this.
