### ISSUE TITLE
How to add routing

### ISSUE THREAD

**Issue by Alan-Guggenheim** [SierraSoftworks/tailscale-udm#20]
Thanks for that nice work. My UDM is installed and running on Tailscale, but it is not showing and subnets. I tried the command sudo tailscale up --advertise-routes=10.0.0.0/24,10.0.1.0/24 but I get a command not found.
Thanks

**Comment by notheotherben** [comment]
Unfortunately the `tailscale` command isn't added to the `$PATH` by default, so you'll need to fully qualify it at `/mnt/data/tailscale/tailscale` - other than that, your command should work just fine (and I don't think you'll need `sudo` since you're `root` already anyway).

**Comment by Alan-Guggenheim** [comment]
Indeed. Thanks
