### ISSUE TITLE
can we use advertise  with this one

### ISSUE THREAD

**Issue by and217** [SierraSoftworks/tailscale-udm#22]
can we use advertise dns subnet with this

**Comment by Avsynthe** [comment]
Hi guys. I'd like to use `--advertise-routes` and `--advertise-exit-node` but I'm a total no0b and don't know how to do this. I tried with tailscale up but it's returning `-sh: tailscale: not found`

**Comment by notheotherben** [comment]
Glad you managed to find the correct path, I'll see what we can do to update the docs to show how to achieve this.

All of this should survive upgrades, I've not encountered any issues so far.
