### ISSUE TITLE
IPv6 curl not working

### ISSUE THREAD

**Issue by Xalaxis** [SierraSoftworks/tailscale-udm#27]
Hi there,

For some reason despite working IPv6 on my network, and being able to `ping6` from the UDM-PRO, unless I append `--ipv4` to all of the curl requests in the script they hang indefinitely. I'm reluctant to do this bypass without understanding why v6 seems to be stuck. Has anyone else been able to run this script on a network with v4 and v6?

**Comment by notheotherben** [comment]
Hi @Xalaxis, these scripts pull information from two places:

1. The bootstrapping script retrieves version information from `api.github.com` and then retrieves a release artifact from `github.com`. In both of these cases it looks like GitHub doesn't offer a native IPv6 endpoint (`dig github.com AAAA` and `dig api.github.com AAAA` don't return an an answer section) and hence will likely cause `curl` to hang.
2. The management script, which installs Tailscale and runs it on the UDM, talks to `pkgs.tailscale.com` which is dual stack and should work correctly.

I'll look to get the bootstrapping script updated to ensure it uses the `--ipv4` flag to bypass [GitHub's lack of dual-stack support](https://github.com/community/community/discussions/10539) for now.

**Comment by Xalaxis** [comment]
Hi Ben, thanks for the quick response!

Unfortunately I'm actually seeing the Tailscale package server fail on IPv6 about 50% of the time as well (it does work occasionally):
![image](https://user-images.githubusercontent.com/12937964/182337705-0fd6f7ca-8994-4aec-8adf-619ef13db89a.png)
![image](https://user-images.githubusercontent.com/12937964/182337746-5c03c8e4-3b21-4ba2-9fed-c356812fc3fd.png)

Perhaps it would be okay to make everything ipv4 only for now?

**Comment by notheotherben** [comment]
Damn, I'll pass that along to the Tailscale folks - I suspect that's not intended 😄.

In the mean time, yeah should be okay to move to IPv4 everywhere, I'll start the process of getting that changed.

**Comment by Xalaxis** [comment]
Hoping it's not just my connection somehow 😅 . I've changed all of the calls in the maintenance script to ``-ipv4`` locally and everything is installed and working :). Thanks for maintaining this!
