### ISSUE TITLE
UDM Pro http issue

### ISSUE THREAD

**Issue by lukasa1993** [SierraSoftworks/tailscale-udm#30]
i have server running in my lan on lets say 192.168.5.5 i have tailscale running on my udm pro which is 192.168.5.1 i have port open in udm so that 80/443 go to 192.168.5.5 and everything works when i am not on tailscale but when i am on tailsacle i use udm pro as exit node and i try to go to my domain port forwarding doesn't work it goes to 192.168.5.1 instead of 5.5  any idea what might cause this ?

**Comment by notheotherben** [comment]
To be honest, I'm struggling to sketch out your specific network topology and what those requests look like.

By my understanding, you've got something like the following:

```mermaid
graph LR
    You1(You) --Web Request - Works--> Server(192.168.5.5)
    Server --Reply--> You1
    You2(You) --Web Request to 192.168.5.5?--> Tailscale --> UDM --X--> Server
    UDM --Reply--> You2
```

Assuming that's correct, I'd like to understand what your "domain" is pointing to - are you making a request to 192.168.5.5 (i.e. is this a DNS A-record for 192.168.5.5) or are you making a request to your UDM's Tailnet domain?

**Comment by lukasa1993** [comment]
example.com -> UDM (ISP IP) -> 5.5

and from external network it works as it should

but from UDM when i request example.com it return UDM itself instead of 5.5

**Comment by lukasa1993** [comment]
oh i have custom dns i'll try it

**Comment by lukasa1993** [comment]
didn't work :( anyway as i understand its udm problem and not tailscale so i'll check with udm support thanks for quick response 👍

**Comment by catgirlinspace** [comment]
was there a fix for this issue? i have the same thing, i host lots of stuff on my home network that i expose to the internet and i can't access these when using my UDM as my exit node.
