### ISSUE TITLE
support for UDR

### ISSUE THREAD

**Issue by Serpentiel** [SierraSoftworks/tailscale-udm#31]
hey 👋 

UDR is a little bit different than UDM, but I believe it should be pretty straightforward to support it, too

please see https://github.com/WireGuard/wireguard-vyatta-ubnt for reference, I believe the key difference is the directory tree

thank you!

**Comment by notheotherben** [comment]
Hey there @Serpentiel, we currently build on top of the unifi-utilities/unifios-utilities `on_boot_script.d` module to provide this functionality for UDM/UDMP. I noticed that there's an outstanding issue (unifi-utilities/unifios-utilities#375) regarding installation on the UDR.

Without a UDR to test against, it's a bit tricky for me to figure out what the necessary directory tree changes - and the repository you've linked takes the approach of building a full `deb` for these targets, which is something Tailscale hasn't (yet) done, and the reason why this repo exists 😄.

**Comment by Serpentiel** [comment]
thank you for your quick response!

I see how it is, let's hope [unifi-utilities/unifios-utilities](https://github.com/unifi-utilities/unifios-utilities) adds support for it!

you can also feel free to ask me to try things out just in case, I have a UDR over here :)

**Comment by lbreggi** [comment]
I can share my UDR too! or I can help to build under some guidence. thanks!

**Comment by epiclulz666** [comment]
i can also provide any testing needed or info needed for the UDR i own 3

**Comment by notheotherben** [comment]
Hi @Serpentiel, @lbreggi, and @epiclulz666 - you'll find a first pass at adding this functionality on #33 along with steps to test that it works before I land this in the mainline release. If you're able to give those steps a try and report any issues, that'd be amazing :)
