### ISSUE TITLE
Install fails due to upstream apt repository issues (404 Not Found/401 Unauthorized)

### ISSUE THREAD

**Issue by mboreilly** [SierraSoftworks/tailscale-udm#58]
I just updated my UDM core OS and tried to reinstall Tailscale, but ended up with errors. It looks like the Debian repo is having issues, but I'm not an expert. Anyone have any thoughts on this? (boostchicken is already installed; it's installer completed without any issues)

From my UDM console:

root@udm:~# curl -sSLq https://raw.github.com/SierraSoftworks/tailscale-udm/main/install.sh | sh
Updating package lists...
Ign:1 http://security.debian.org stretch/updates InRelease
Ign:2 http://deb.debian.org/debian stretch InRelease
Err:3 http://security.debian.org stretch/updates Release
  404  Not Found [IP: 151.101.42.132 80]
Ign:4 http://deb.debian.org/debian stretch-updates InRelease
Ign:5 http://deb.debian.org/debian stretch-backports InRelease
Err:6 http://deb.debian.org/debian stretch Release
  404  Not Found [IP: 151.101.42.132 80]
Err:7 http://deb.debian.org/debian stretch-updates Release
  404  Not Found [IP: 151.101.42.132 80]
Err:8 http://deb.debian.org/debian stretch-backports Release
  404  Not Found [IP: 151.101.42.132 80]
Hit:10 https://apt-release-candidate.artifacts.ui.com stretch InRelease
Hit:11 https://apt-beta.artifacts.ui.com stretch InRelease
Hit:12 https://apt.artifacts.ui.com stretch InRelease
Reading package lists... Done 
E: The repository 'http://security.debian.org stretch/updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://deb.debian.org/debian stretch-backports Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@udm:~#

**Comment by bdollerup** [comment]
I can verify the issue. I just tried to install the script on my UDM pro and I got the same result that @mboreilly got. 
```
Updating package lists...
Ign:1 http://deb.debian.org/debian stretch InRelease
Ign:2 http://security.debian.org stretch/updates InRelease
Ign:3 http://deb.debian.org/debian stretch-updates InRelease
Err:4 http://security.debian.org stretch/updates Release
  404  Not Found [IP: 199.232.42.132 80]
Ign:5 http://deb.debian.org/debian stretch-backports InRelease
Err:6 http://deb.debian.org/debian stretch Release
  404  Not Found [IP: 199.232.42.132 80]
Err:7 http://deb.debian.org/debian stretch-updates Release
  404  Not Found [IP: 199.232.42.132 80]
Err:8 http://deb.debian.org/debian stretch-backports Release
  404  Not Found [IP: 199.232.42.132 80]
Ign:9 https://apt-release-candidate.artifacts.ui.com stretch InRelease
Hit:10 https://apt.artifacts.ui.com stretch InRelease
Ign:11 https://apt-beta.artifacts.ui.com stretch InRelease
Err:13 https://apt-release-candidate.artifacts.ui.com stretch Release
  401
Err:14 https://apt-beta.artifacts.ui.com stretch Release
  401
Reading package lists... Done
E: The repository 'http://security.debian.org stretch/updates Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://deb.debian.org/debian stretch Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://deb.debian.org/debian stretch-updates Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://deb.debian.org/debian stretch-backports Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://apt-release-candidate.artifacts.ui.com stretch Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://apt-beta.artifacts.ui.com stretch Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by notheotherben** [comment]
Hi folks, this does look like an issue with the Ubiquiti apt repositories, best I can see, this problem seems to be resolved now but please do let me know if you continue to see the same problem.

If you do, can I suggest you try running the following to get some debug information and share it in the https://community.ui.com forums so that they can take a look?

```bash
echo '# Get the current OS version'
cat /etc/os-release

echo '# Get the current firmware version'
/usr/bin/ubnt-device-info firmware_detail

echo '# Run apt update to reproduce the issue'
apt update
```

For example, on my device this results in the following:

```
# Get the current OS version
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
# Get the current firmware version
3.0.20
# Run apt update to reproduce the issue
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease                                                                                                                                  
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease                                                                                                                          
Hit:4 http://deb.debian.org/debian bullseye-backports InRelease                                                                                                                        
Get:5 https://pkgs.tailscale.com/stable/debian stretch InRelease                                                                                                                 
Hit:6 https://apt.artifacts.ui.com bullseye InRelease               
Hit:7 https://apt-release-candidate.artifacts.ui.com bullseye InRelease
Fetched 6015 B in 2s (3917 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
33 packages can be upgraded. Run 'apt list --upgradable' to see them.
```

**Comment by bdollerup** [comment]
Third time's the charm:

I ran the script again and this time I got this:
```
Installation complete, run '/data/tailscale/manage.sh start' to start Tailscale
Installation complete, run '/data/tailscale/manage.sh start' to start Tailscale
Tailscaled started successfully
Running tailscale up to configure interface...
```
And here's my data:
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

echo '# Get the current firmware version'
/usr/bin/ubnt-device-info firmware_detail

3.0.20

echo '# Run apt update to reproduce the issue'
apt update

Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian bullseye-backports InRelease [49.0 kB]
Get:5 https://pkgs.tailscale.com/stable/debian stretch InRelease
Hit:6 https://apt.artifacts.ui.com bullseye InRelease
Get:7 http://deb.debian.org/debian bullseye-backports/main arm64 Packages [417 kB]
Fetched 516 kB in 2s (323 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
35 packages can be upgraded. Run 'apt list --upgradable' to see them.
```

All is good and up and running. Thanks!!!

**Comment by bnhf** [comment]
Worked for me today too on a UDM-SE running 3.0.18. I did see a "context canceled" at the end of the script, and it dropped to the prompt rather than waiting for authentication. Didn't seem to matter though, as I was still able to authenticate, and Tailscale appears to be working so far.

I take it these steps to setup subnet routing from the Tailscale Wiki aren't required on the UDM:

![screenshot-tailscale com-2023 05 15-15_57_17](https://github.com/SierraSoftworks/tailscale-udm/assets/41088895/2d6f63d7-8533-4f7d-bb98-1ab4a28e9c44)

The steps listed in the README here jump right to ```tailscale up --advertise-routes=192.168.1.0/24```
