### ISSUE TITLE
Unable to Install on UDMP

### ISSUE THREAD

**Issue by its-nolan** [SierraSoftworks/tailscale-udm#65]
Hi
I am trying to install TailScale on a UDMP with version 2.5.17 but getting errors before it installs successfully. Attached is the output of the SSH session. 
[TailScale UDMP Install Log.txt](https://github.com/SierraSoftworks/tailscale-udm/files/11952172/TailScale.UDMP.Install.Log.txt)

**Comment by notheotherben** [comment]
Hi there @nolan-lynch, I believe this is the same issue mentioned in #58 - unfortunately it's something that appears to happen with the upstream debian repos from time to time and my best advice is to try again in a day or two and see if the issue has been resolved.

**Comment by MRobi1** [comment]
@notheotherben "best advice is to try again in a day or two" Is this still the best advice or have you uncovered a workaround in the past few months? Been having this issue for almost a month now.

**Comment by notheotherben** [comment]
Hi @MRobi1 - can you run the following on your UDM and confirm whether it works or not?

```sh
apt update
```

If you're getting the same issues with Debian repositories missing the Release file then it is unfortunately an issue with the upstream package repositories rather than an issue with this script and is something you'd need to troubleshoot separately.

**Comment by MRobi1** [comment]
```
tee /etc/apt/sources.list &> /dev/null << EOF
deb http://deb.debian.org/debian/ bullseye main contrib non-free
deb http://deb.debian.org/debian/ bullseye-updates main contrib non-free
deb http://deb.debian.org/debian/ bullseye-backports main
deb http://security.debian.org/debian-security bullseye-security main contrib non-free
EOF
```
This allowed the installation to complete.
