### ISSUE TITLE
TAILSCALE_FLAGS unused in 2.x version

### ISSUE THREAD

**Issue by pkwarren** [SierraSoftworks/tailscale-udm#69]
After upgrading from 1.x to 2.x, I had edited `tailscale-env` to add some additional options to be passed to `tailscale up`. However, it appears `TAILSCALE_FLAGS` is no longer used in unios_2.x.sh.

**Comment by notheotherben** [comment]
Let me chase that down, the big delta between 1.x and 2.x is that on 1.x we're manually installing the Tailscale `.tar.gz` and on 2.x we're installing using the Tailscale `apt` repository (and as a result there are some differences in the launch scripts). I'll see if we can get the flags injected into `/etc/default/tailscaled` during installation.
