### ISSUE TITLE
Exit Node selected but offline

### ISSUE THREAD

**Issue by razzcrazy1** [SierraSoftworks/tailscale-udm#71]
Hi Sierra Softworks,

I installed the latest version of tailscale-udm and "status" and "netcheck" outputs are successful I connected 
the UDM to an exit node but I received the following exit-node output lis status. It appears my UDM is not able to 
connect to my VPS although I am able to ping the between the UDM and VPS and a client device. 

 tailscale -- exit-node list

 100.76.xx.xx     xxx.tailee24b.ts.net     -           -         -                        
 100.91.x.xxx    xxx.tailee24b.ts.net     -           -         selected but offline

Current configuration: 

tailscale up --exit-node=100.9.x.xxx   --exit-node-allow-lan-access=true --advertise-routes=192.168.x.0/24,192.168.x.0/24,192.168.x.0/24 --ssh

Any assistance is greatly appreciated.

**Comment by notheotherben** [comment]
Hi there, right now we're using userspace networking for the reasons outlined in #68 and as a result there's no simple way to route traffic from your UDM onto your Tailnet (or out via an exit node). If you'd like, you can follow some of the guidance in #51 to see if it works for you (but I'll caution that it's not supported by this script for a reason).
