### ISSUE TITLE
Not starting / surviving reboots.

### ISSUE THREAD

**Issue by Blindside10** [SierraSoftworks/tailscale-udm#8]
Noticed today that tailscale wasn't starting automatically and couldn't be manually started either required a fresh install to get going again.

**Comment by notheotherben** [comment]
Can you confirm that you've got the [boostchicken/on-boot-script](https://github.com/boostchicken/udm-utilities/tree/master/on-boot-script#steps) installed on your UDM by following those linked steps? I've not had any issues on my side with this aspect but it won't work correctly if you don't have the boostchicken stuff installed.

**Comment by Blindside10** [comment]
Yeah, I have that installed. It's weird at other sites reboots seem to not be a problem. I am just sharing with you what all I can see from the cli. I think that's what it should look like right? 
`  ___ ___      .__________.__
 |   |   |____ |__\_  ____/__|
 |   |   /    \|  ||  __) |  |   (c) 2010-2021
 |   |  |   |  \  ||  \   |  |   Ubiquiti Inc.
 |______|___|  /__||__/   |__|
            |_/                  http://www.ui.com

      Welcome to UniFi Dream Machine!
# ls -la
total 4
drwx------    1 root     root            80 Oct  4 07:36 .
drwxr-xr-x    1 root     root           200 Oct  3 20:04 ..
-rw-------    1 root     root             7 Oct  4 07:36 .ash_history
drwxr-xr-x    2 root     root            60 Oct  3 20:04 .ssh
# cd /mnt/data/
# ls
713a-udmpro-1.9.3-c467d3f8c4e74e4281ede75c58a9d3fb.bin
crash-data
fw.bin
log
lost+found
on_boot.d
podman
ssh
system
tailscale
traces
udapi-config
ui-db
ulcmd
unifi-os
# cd on_boot.d/
# ls
10-tailscaled.sh`

**Comment by notheotherben** [comment]
Yeah, that all looks fine to me - which firmware version are you running on your sites that are working/not working? (I noticed something in the boostchicken repo about issues with the latest 1.11 betas).

**Comment by Blindside10** [comment]
I don't know how much help this will be but basically anytime I run a command regarding tailscale I get a response like this which is expected, because the service hasn't started. 
```# /mnt/data/tailscale/tailscale status
failed to connect to local tailscaled; it doesn't appear to be running (sudo systemctl start tailscaled ?)
# ```

**Comment by Blindside10** [comment]
Oh my goodness. I feel horrible for leaving this open for so long. I reinstalled everything and it worked first try no problem at all. Thank you! I will close now.
