### ISSUE TITLE
UniFi OS v4

### ISSUE THREAD

**Issue by Forsaked** [SierraSoftworks/tailscale-udm#86]
There is a new early access version of the UDMP firmware, which is version 4.0.3, the installer exits out with following message:

Unsupported UniFi OS version (v4).
Please provide the following information to us on GitHub:
/usr/bin/ubnt-device-info firmware_detail
4.0.3
/etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by notheotherben** [comment]
Thanks for the report and thank you @bslatyer for the contribution fixing this. You should be able to use the latest v2.6.0 release to deploy on UniFi OS 4.x; but please do let me know if you run into problems.

**Comment by Forsaked** [comment]
Just installed, works as it should, both exit node and subnet router are also working.

**Comment by Forsaked** [comment]
Can be closed in my opinion, thank you both!
