### ISSUE TITLE
allow overriding TAILSCALED_FLAGS during Installation

### ISSUE THREAD

**Issue by jasonwbarnett** [SierraSoftworks/tailscale-udm#98]
First, thank you for all the amazing work on this project. I recently got a change merged upstream (https://github.com/tailscale/tailscale/pull/10828) that enables the UDM-Pro to act as a [subnet router](https://tailscale.com/kb/1019/subnets) without requiring any custom ip rules, which is a great step forward.

To make this even more seamless, I’d like to propose an enhancement that allows users to override the default `TAILSCALED_FLAGS` during installation, avoiding the need to modify `/etc/default/tailscaled` after installation.

From what I’ve seen, variables in `package/tailscale-env` are sourced and override any shell variables set. I’d be happy to implement this change myself but wanted to ask for guidance to ensure the approach aligns with your expectations and avoids unnecessary complexity.

Would you be open to a contribution in this area? If so, any tips or preferences for implementation would be greatly appreciated!

**Comment by notheotherben** [comment]
Awesome work getting that included, I had been following along for a while hoping we'd see it land.

In terms of supporting overrides during the install process, I'm absolutely open to doing so - it's something we already support to a lesser degree with the `TAILSCALE_VERSION` environment variable and I see no reason why we couldn't introduce a new one.

In terms of implementation, the `package/tailscale-env` file is loaded to configure the install/setup scripts (and in the case of the UniFi OS 1.x implementation, to govern Tailscale's operation). In the case of the UniFi 2.x+ [implementation](https://github.com/SierraSoftworks/tailscale-udm/blob/b2c8e4ea89fd6657df84e1756b9eb1172d42aa2e/package/unios_2.x.sh#L58-L70) we source it, and then project those values into the `/etc/default/tailscaled` file using `sed`. 

Shout if I can give you a hand with anything there, and especially when it comes to implementing the tests to validate that this all works correctly (there's an ["interesting" bash-based test suite](https://github.com/SierraSoftworks/tailscale-udm/blob/main/tests/install.2.x.test.sh) that mocks out much of this stuff but might not be intuitive).
